import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/firebase";
import { useState } from "react";
import Link from "next/link";

export default function Home() {
  const [login, setLogin] = useState(false);
  onAuthStateChanged(auth, (user) => {
    if (user) {
      const uid = user.uid;
      console.log("-----user-----", user.displayName);
      setLogin(true);
      //   setUserName(user.displayName);
      // ...
    } else {
      console.log("--- not signed in----");
      setLogin(false);
      // User is signed out
      // ...
    }
  });

  const LoginButton = !login ? (
    <div className="flex-container">
      <h1>You are not currently signed in</h1>
      <Link href="/signin">
        <button>Sign in here</button>
      </Link>
    </div>
  ) : (
    <div className="flex-container">
      You are signed in! Check out your <Link href="/user">user page</Link>
    </div>
  );
  return (
    <>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">{LoginButton}</main>
    </>
  );
}
