import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/firebase";
import { useState } from "react";
import Link from "next/link";
import SignInModal from "@/components/SignInModal";

export default function Home() {
  const [login, setLogin] = useState(false);
  const [currentUser, setCurrentUser] = useState<string | null>("");

  const handleLogout = () => {
    auth.signOut();
  };

  onAuthStateChanged(auth, (user) => {
    if (user && user.emailVerified) {
      const uid = user.uid;
      console.log("-----user-----", user);
      setCurrentUser(user.displayName);
      setLogin(true);

      // ...
    } else {
      console.log("--- not signed in----");
      setLogin(false);
      // User is signed out
      // ...
    }
  });

  const LoginButton = !login ? (
    <div className="flex-container">
      <h1>You are not currently signed in</h1>
      <SignInModal />
    </div>
  ) : (
    <div className="flex-container">
      <h1>Hi,{currentUser}. You are signed in!</h1>
      <Link href="/">
        <button onClick={handleLogout}>Log out</button>
      </Link>
    </div>
  );

  return (
    <>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">{LoginButton}</main>
    </>
  );
}
