import { redirect } from "next/navigation";
import Link from "next/link";
import { useEffect, useState } from "react";
import { auth } from "../../firebase";
import Head from "next/head";
const handleLogout = () => {
  auth.signOut();
};

export default function UserInfo() {
  const [loggedIn, setLoggedIn] = useState(false);
  useEffect(() => {
    auth.onAuthStateChanged(function (user) {
      if (user) {
        setLoggedIn(true);
      } else {
        setLoggedIn(false);
      }
    });
  }, []);

  const TextPrompt = loggedIn ? (
    <div className="flex-container">
      <h1>You have succesfully logged in! </h1>
      <Link href="/">
        <button onClick={handleLogout}>Log out</button>
      </Link>
    </div>
  ) : (
    <div className="flex-container">
      <h1>
        Insuffiecent permissions, please sign in{" "}
        <Link href="/signin">here</Link>
      </h1>
    </div>
  );

  return (
    <>
      <Head>
        <title>Success</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">{TextPrompt}</main>
    </>
  );
}
